### PR TITLE
cran compatibility

### PR DESCRIPTION
**Pull request by bernhard-da**
@tenderle thx for the package.

in this pull request, i did not make any "real" changes, just fixing some documentation issues, fixing imports and make cran-checks happy. 

At the end of the day, this package (as well as cellKey) should be on CRAN so we can import easily from each other. For the time being, there is one issue left to fix

```
devtools::load_all()
params <- pt_create_pParams(D=5, V=2, js=2, label="Example")
ptable_destatis <- pt_create_pTable(params=params, type="destatis")
```

returns an error which is bad because you have this code in your examples.

### CODE REVIEW

**Comment by bernhard-da** [comment]
the error is:
```
error in is.nloptr(ret) : length(lb) != length(x0) 
```

**Comment by tenderle** [comment]
@bernhard-da thx. I did some minor fixes after @ppdewolf highlighted some bugs. However, you have fixed some more issues. Unfortunately, I have no write access to this repository. Could you repeat the pull request to tenderle/ptable?

**Comment by ppdewolf** [comment]
@tenderle I think I've given you write access now to the sdctools/ptable repository

**Comment by tenderle** [comment]
Thx, @ppdewolf 

Since it's the first time I push and commit a R-package to github, I've messed up my master branch. Therefore, I manually do the changes from @bernhard-da and push a new branch to my repo and then update the sdc-repo afterwards. Thx to both of you.

**Pull request closed without merging**
