### PR TITLE
First release of the R-package "ptable"

### PR DESCRIPTION
**Pull request by tenderle**
Dear @ppdewolf, dear @bernhard-da,

I have finished the first version of our R-package which could be used for first tests. I have done some changes regarding the labels of the ptable (which is imported/read by your tools) as you can see.

Could you please update the fork?

Thanks,
Tobias

### CODE REVIEW

**Comment by ppdewolf** [comment]
Fork updated, I think... :wink:

**Comment by tenderle** [comment]
Thx, @ppdewolf. It seems to work :+1: 

To be more specific what I have changed: I replaced the header of the csv-output file. While the old version (e.g. the example _20160511_szenario_5a.csv_ I sent to you) was labeled with german (kum=cumulated ;-) shortcuts as follows
`i | j | p | kum_p_u | kum_p_o | diff`
I have updated (i.e. renamed the header and reduced the file by means of less columns) the output when using the function `pt_export(...)` as described in the readme:
`i | v | p_int_ub`
where `v` perturbation value (replaces `diff`) and `p_int_ub` upper bound of the probability intervals (replaces `kum_p_o`).

If you need more than these three columns for tauargus (e.g. do you need `p`?), I will rewrite the `pt_export` file.

**Comment by ppdewolf** [comment]
Well, I thought that the `p` would stay anyway and used that to calculate the `kum_p_o` myself 🤣 
So I only used the first three rows `i | j | p` and disregarded the rest.
We should think about what would be usefull to users about the ptable in this format. In my view the `p` has more meaning to users. The `kum_p_o` is helpful in applying the method though.

**Comment by ppdewolf** [comment]
And perhaps some thoughts on the "continuous variable" version of the ptable format?

**Comment by bernhard-da** [comment]
@tobias

in a few minutes you'll get a pull request making the package almost cran
ready :)

there is only one issue left, some of your examples (as indicated in the
pull request) return an error...

greets,
bernhard

**Comment by tenderle** [comment]
@ppdewolf Thx, now it should work and you will receive all required columns needed for tauargus when using `pt_export(...)`.

However, I will return to your remark and question when I am back in office again (in about two weeks).

**Comment by ppdewolf** [comment]
Enjoy your holidays!

**Pull request merged**
